import HomeView from "@/view/HomeView";

export const metadata = {
  title: "Grammar Correction App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <HomeView/>
    </div>
  );
}

export default page